In [1]:
import pandas as pd

stations_df = pd.DataFrame(
    [
        [768328, 'GAREY', 45.623, 44.1],
        [717241, 'FAIRPLEX', 43.76, 42.3],
        [717243, 'DUDLEY', 44.13, 42.6],
        [716187, 'CLEVELAND', 44.68, 43.2],
        [717247, 'WHITE', 45.16, 43.7],
        [717251, 'ORANGE GROVE', 46.01, 44.5],
        [717254, 'TOWNE', 46.56, 45.1],
    ],
    columns=['ID', 'Description', 'PM', 'Abs PM']
)
stations_df

       ID   Description      PM  Abs PM
0  768328         GAREY  45.623    44.1
1  717241      FAIRPLEX  43.760    42.3
2  717243        DUDLEY  44.130    42.6
3  716187     CLEVELAND  44.680    43.2
4  717247         WHITE  45.160    43.7
5  717251  ORANGE GROVE  46.010    44.5
6  717254         TOWNE  46.560    45.1

In [2]:
MISSING_DATA_FILE = r"C:\Users\dknom\Documents\school\CE5620_traffic_analysis\hw\CE5620-Homework4\S5_768328_flow_occ_missing_data02112026.xlsx"

missing_data_df = pd.read_excel(MISSING_DATA_FILE)
missing_data_df

,Sample Time,768328 Lane 1 Flow,768328 Lane 2 Flow,768328 Lane 3 Flow,768328 Lane 4 Flow,768328 Lane 1 Occupancy (%),768328 Lane 2 Occupancy (%),768328 Lane 3 Occupancy (%),768328 Lane 4 Occupancy (%),768328 Lane 1 G-Factor (22) Speed,768328 Lane 2 G-Factor (22) Speed,768328 Lane 3 G-Factor (22) Speed,768328 Lane 4 G-Factor (22) Speed
0,2026-02-11 00:00:08,3.0,6.0,1.0,1.0,1.78,3.72,2.89,0.50,84.269663,80.645161,17.301038,100.000000
1,2026-02-11 00:00:38,4.0,4.0,5.0,5.0,2.22,2.28,9.22,6.22,90.090090,87.719298,27.114967,40.192926
2,2026-02-11 00:01:08,3.0,4.0,3.0,2.0,1.72,2.39,3.72,2.00,87.209302,83.682008,40.322581,50.000000
3,2026-02-11 00:01:38,6.0,4.0,5.0,2.0,3.61,2.28,11.50,1.39,83.102493,87.719298,21.739130,71.942446
4,2026-02-11 00:02:08,2.0,4.0,2.0,2.0,1.11,4.50,5.61,2.22,90.090090,44.444444,17.825312,45.045045
...,...,...,...,...,...,...,...,...,...,...,...,...,...
2602,2026-02-11 23:57:38,4.0,3.0,3.0,3.0,2.61,1.89,4.39,6.00,76.628352,79.365079,34.168565,25.000000
2603,2026-02-11 23:58:08,2.0,1.0,1.0,4.0,1.22,0.50,0.61,5.28,81.967213,100.000000,81.967213,37.878788
2604,2026-02-11 23:58:38,4.0,3.0,3.0,3.0,2.22,1.78,3.72,3.00,90.090090,84.269663,40.322581,50.000000
2605,2026-02-11 23:59:08,2.0,8.0,3.0,3.0,1.11,4.72,8.28,1.78,90.090090,84.745763,18.115942,84.269663
2606,2026-02-11 23:59:38,4.0,7.0,2.0,2.0,2.22,4.28,2.72,1.50,90.090090,81.775701,36.764706,66.666667

In [ ]:
import glob

same_day_files = glob.glob(r'C:\Users\dknom\Documents\school\CE5620_traffic_analysis\hw\CE5620-Homework4\*02112026.xlsx')